"""modified exam-table4

Revision ID: 1a7b6598a92f
Revises: 27c5163d8ccb
Create Date: 2026-03-06 10:32:19.013377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7b6598a92f'
down_revision: Union[str, Sequence[str], None] = '27c5163d8ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_end_time'), ['end_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_end_time'))

    # ### end Alembic commands ###
