"""modified exam-table3

Revision ID: 27c5163d8ccb
Revises: ebe3766b2dca
Create Date: 2026-03-06 10:13:09.161591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c5163d8ccb'
down_revision: Union[str, Sequence[str], None] = 'ebe3766b2dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Interval(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
