"""reorganized code

Revision ID: 33ed4b8b01ea
Revises: 3e913c7ebfd8
Create Date: 2026-02-25 15:50:19.345079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ed4b8b01ea'
down_revision: Union[str, Sequence[str], None] = '3e913c7ebfd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_id'))

    op.drop_table('exam_questions')
    op.drop_table('user_roles')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    op.drop_table('user_profiles')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_id'))

    op.drop_table('courses')
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_answers_id'))

    op.drop_table('user_answers')
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_courses_id'))

    op.drop_table('student_courses')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_id'))

    op.drop_table('universities')
    with op.batch_alter_table('exam_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempt_id'))

    op.drop_table('exam_attempt')
    op.drop_table('roles')
    op.drop_table('role_permissions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_id'))

    op.drop_table('questions')
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculties_id'))

    op.drop_table('faculties')
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_id'))

    op.drop_table('exam')
    with op.batch_alter_table('attempt_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_question_id'))

    op.drop_table('attempt_question')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_id'))

    op.drop_table('news')
    op.drop_table('permissions')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_id'))

    op.drop_table('modules')
    op.drop_table('users')
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_choices_id'))

    op.drop_table('choices')
    op.drop_table('addresses')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('faculty_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], name=op.f('fk_departments_faculty_id_faculties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('addresses',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('street', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('country', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_table('choices',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_choices_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('id', name=op.f('uq_users_id')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('modules',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('department_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('faculty_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_modules_department_id_departments')),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], name=op.f('fk_modules_faculty_id_faculties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules'))
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_id'), ['id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=19), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_permissions_id')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('news',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_news_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_id'), ['id'], unique=False)

    op.create_table('attempt_question',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('attempt_id', sa.VARCHAR(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(), nullable=False),
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_question_id'), ['id'], unique=False)

    op.create_table('exam',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('maximum_marks', sa.INTEGER(), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=False),
    sa.Column('exam_type', sa.VARCHAR(length=15), server_default=sa.text("'model exit exam'"), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exam_created_by_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_id'), ['id'], unique=False)

    op.create_table('faculties',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('university_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('code', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_faculties_university_id_universities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculties')),
    sa.UniqueConstraint('code', name=op.f('uq_faculties_code'))
    )
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculties_id'), ['id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('exam_id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('marks', sa.INTEGER(), nullable=True),
    sa.Column('department_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('module_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_questions_course_id_courses')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_questions_department_id_departments')),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_questions_module_id_modules')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_id'), ['id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('permission_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_role_permissions_id')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permission'))
    )
    op.create_table('roles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=12), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_roles_id')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('exam_attempt',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('exam_id', sa.VARCHAR(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('is_passed', sa.BOOLEAN(), nullable=True),
    sa.Column('is_expired', sa.BOOLEAN(), nullable=True),
    sa.Column('is_graded', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempt_id'), ['id'], unique=False)

    op.create_table('universities',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('address_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_universities_address_id_addresses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universities')),
    sa.UniqueConstraint('code', name=op.f('uq_universities_code'))
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_id'), ['id'], unique=False)

    op.create_table('student_courses',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('enrollment_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_student_courses_course_id_courses')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_courses_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_courses'))
    )
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_courses_id'), ['id'], unique=False)

    op.create_table('user_answers',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('attempt_id', sa.VARCHAR(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(), nullable=False),
    sa.Column('selected_option_id', sa.VARCHAR(), nullable=True),
    sa.Column('attempt_question_id', sa.VARCHAR(), nullable=True),
    sa.Column('marks_awarded', sa.FLOAT(), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempt.id'], ),
    sa.ForeignKeyConstraint(['attempt_question_id'], ['attempt_question.id'], name=op.f('fk_user_answers_attempt_question_id_attempt_question')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['choices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_answers_id'), ['id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('module_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('department_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('credits', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_courses_department_id_departments')),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_courses_module_id_modules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('code', name=op.f('uq_courses_code'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_id'), ['id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mname', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lname', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bio', sa.VARCHAR(length=255), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('birth_date', sa.VARCHAR(length=10), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('social_links', sa.VARCHAR(length=255), nullable=True),
    sa.Column('preferences', sa.VARCHAR(length=255), nullable=True),
    sa.Column('settings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=30), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_user_profiles_id'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_revoked', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('revoked_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=1)

    op.create_table('user_roles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('assigned_by', sa.VARCHAR(length=36), nullable=False),
    sa.Column('assigned_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name=op.f('uq_user_roles_id')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_role'))
    )
    op.create_table('exam_questions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('exam_id', sa.VARCHAR(), nullable=False),
    sa.Column('question_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id', 'exam_id', 'question_id')
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_id'), ['id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('enrollment_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_students_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('enrollment_number', name=op.f('uq_students_enrollment_number')),
    sa.UniqueConstraint('id', name=op.f('uq_students_id'))
    )
    # ### end Alembic commands ###
