"""redesigning with mixins

Revision ID: 35d467643a56
Revises: 8a2e07f33a4e
Create Date: 2026-03-02 10:09:27.271394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d467643a56'
down_revision: Union[str, Sequence[str], None] = '8a2e07f33a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_departments')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('faculty_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institute_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'institutes', ['institute_id'], ['id'])

    with op.batch_alter_table('institutes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_school_slug_per_university'), type_='unique')
        batch_op.create_unique_constraint('uq_institute_slug_per_university', ['slug', 'university_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_institute_slug_per_university', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_school_slug_per_university'), ['slug', 'university_id'])

    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('institute_id')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.alter_column('faculty_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    op.create_table('_alembic_tmp_departments',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('years_of_study', sa.INTEGER(), nullable=False),
    sa.Column('faculty_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
