"""linking question with others

Revision ID: 3e913c7ebfd8
Revises: 9e61dda8d18c
Create Date: 2026-02-16 12:30:41.132640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e913c7ebfd8'
down_revision: Union[str, Sequence[str], None] = '9e61dda8d18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('course_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('module_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_questions_module_id_modules'), 'modules', ['module_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_questions_department_id_departments'), 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_questions_course_id_courses'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks_awarded', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.drop_column('is_correct')
        batch_op.drop_column('marks_awarded')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_questions_course_id_courses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_questions_department_id_departments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_questions_module_id_modules'), type_='foreignkey')
        batch_op.drop_column('module_id')
        batch_op.drop_column('course_id')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
