"""redesigning with mixins1

Revision ID: 592af6616bcd
Revises: 35d467643a56
Create Date: 2026-03-02 10:26:47.558806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592af6616bcd'
down_revision: Union[str, Sequence[str], None] = '35d467643a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_faculties')
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institute_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_faculties_institute_id_institutes', 'institutes', ['institute_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_faculties_institute_id_institutes', type_='foreignkey')
        batch_op.drop_column('institute_id')

    op.create_table('_alembic_tmp_faculties',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('university_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('institute_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], name=op.f('fk_faculties_institute_id_institutes')),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
