"""modifying 2 refresh-token table

Revision ID: cdc6e04e72cc
Revises: 0504a026424b
Create Date: 2026-02-01 14:56:43.332813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc6e04e72cc'
down_revision: Union[str, Sequence[str], None] = '0504a026424b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_exam')
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_exam_created_by_users'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_exam_created_by_users'), type_='foreignkey')
        batch_op.drop_column('created_by')

    op.create_table('_alembic_tmp_exam',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('maximum_marks', sa.INTEGER(), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=False),
    sa.Column('exam_type', sa.VARCHAR(length=15), server_default=sa.text("'model exit exam'"), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exam_created_by_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
